version: 0.2

phases:
  build:
    commands:
      - cd src
      - dotnet restore
      - dotnet lambda deploy-function --region us-east-1 -c Release -f netcoreapp1.0 -frun dotnetcore1.0 -fh MyProject::getStackExchange.Alexa.Service::GetResponse -fn StackExchangeAlexaResponse
